"""add section count

Revision ID: 4b61c4cc76c8
Revises: c544c29bbe22
Create Date: 2025-02-20 00:58:49.376959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b61c4cc76c8'
down_revision: Union[str, None] = 'c544c29bbe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('sections_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'sections_count')
    # ### end Alembic commands ###
