"""init

Revision ID: 6c0e3c3a4256
Revises: 
Create Date: 2025-02-19 17:30:08.839419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e3c3a4256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_type', sa.Enum('CARDS', 'TRUTH_DARE', 'BORRD_GAME', 'SCRATH', name='game'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('question_level', sa.Enum('EASY', 'MEDIUM', 'HARD', 'INTENSE', 'SUPER', name='gamelevel'), server_default='EASY', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('ADMIN', 'USER', name='usertype'), server_default='USER', nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('game_level', sa.Enum('EASY', 'MEDIUM', 'HARD', 'INTENSE', 'SUPER', name='gamelevel'), server_default='EASY', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('game_data')
    # ### end Alembic commands ###
