"""add section count

Revision ID: c544c29bbe22
Revises: 75e56aa4321d
Create Date: 2025-02-20 00:56:12.197639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c544c29bbe22'
down_revision: Union[str, None] = '75e56aa4321d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'conclusion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('article', 'sections_count')
    # ### end Alembic commands ###
